//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float3 cameraPosition_w;
//   float4 fog;
//   
//   struct
//   {
//       struct
//       {
//           float4 ambientColor;
//
//       } ambient;
//       
//       struct
//       {
//           float3 direction_w;
//           float4 diffuseColor;
//           float4 specularColor;
//
//       } parallelSpecular;
//       
//       struct
//       {
//           float3 direction_w;
//           float4 diffuseColor;
//
//       } parallel[2];
//       
//       struct
//       {
//           float3 position_w;
//           float4 diffuseColor;
//           float4 attenuation;
//           float4 specularColor;
//
//       } pointSpecular;
//       
//       struct
//       {
//           float3 position_w;
//           float4 diffuseColor;
//           float4 attenuation;
//
//       } point_id[4];
//       
//       struct
//       {
//           float3 cameraPosition_o;
//           float3 direction_o;
//           float4 diffuseColor;
//           float4 specularColor;
//
//       } dot3;
//
//   } lightData;
//   
//   struct
//   {
//       float4 diffuseColor;
//       float4 ambientColor;
//       float4 specularColor;
//       float4 emissiveColor;
//       float specularPower;
//
//   } material;
//   
//   float4x4 objectWorldCameraProjectionMatrix;
//   float4x4 objectWorldMatrix;
//
//
// Registers:
//
//   Name                              Reg   Size
//   --------------------------------- ----- ----
//   objectWorldCameraProjectionMatrix c0       4
//   objectWorldMatrix                 c4       3
//   cameraPosition_w                  c8       1
//   fog                               c10      1
//   material                          c11      4
//   lightData                         c16     24
//

    vs_2_0
    def c7, 1.44269502, 0, 1, 0
    dcl_position v0
    dcl_normal v1
    dcl_color v2
    dcl_texcoord v3
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    dp4 r0.x, v0, c4
    dp4 r0.y, v0, c5
    dp4 r0.z, v0, c6
    add r1.xyz, -r0, c8
    dp3 r0.w, r1, r1
    mul r0.w, r0.w, c10.w
    mul r0.w, r0.w, c7.x
    exp r0.w, r0.w
    rcp oFog, r0.w
    dp3 r1.x, v1, c4
    dp3 r1.y, v1, c5
    dp3 r1.z, v1, c6
    nrm r2.xyz, r1
    dp3 r0.w, r2, c17
    max r0.w, r0.w, c7.y
    mov r1, c18
    mad r1, r0.w, r1, c14
    dp3 r0.w, r2, c20
    max r0.w, r0.w, c7.y
    mad r1, r0.w, c21, r1
    dp3 r0.w, r2, c22
    max r0.w, r0.w, c7.y
    mad r1, r0.w, c23, r1
    mov r3.x, c7.z
    add r4.xyz, -r0, c24
    dp3 r3.z, r4, r4
    rsq r3.w, r3.z
    mul r3.y, r3.w, r3.z
    dp4 r0.w, c26, r3
    mul r3.xyz, r3.w, r4
    dp3 r2.w, r2, r3
    max r2.w, r2.w, c7.y
    rcp r0.w, r0.w
    mul r0.w, r0.w, r2.w
    mad r1, r0.w, c25, r1
    mov r3.x, c7.z
    add r4.xyz, -r0, c28
    dp3 r3.z, r4, r4
    rsq r3.w, r3.z
    mul r3.y, r3.w, r3.z
    dp4 r0.w, c30, r3
    mul r3.xyz, r3.w, r4
    dp3 r2.w, r2, r3
    max r2.w, r2.w, c7.y
    rcp r0.w, r0.w
    mul r0.w, r0.w, r2.w
    mad r1, r0.w, c29, r1
    mov r3.x, c7.z
    add r4.xyz, -r0, c31
    dp3 r3.z, r4, r4
    rsq r3.w, r3.z
    mul r3.y, r3.w, r3.z
    dp4 r0.w, c33, r3
    mul r3.xyz, r3.w, r4
    dp3 r2.w, r2, r3
    max r2.w, r2.w, c7.y
    rcp r0.w, r0.w
    mul r0.w, r0.w, r2.w
    mad r1, r0.w, c32, r1
    mov r3.x, c7.z
    add r4.xyz, -r0, c34
    add r0.xyz, -r0, c37
    dp3 r3.z, r4, r4
    rsq r3.w, r3.z
    mul r3.y, r3.w, r3.z
    dp4 r0.w, c36, r3
    mul r3.xyz, r3.w, r4
    dp3 r2.w, r2, r3
    max r2.w, r2.w, c7.y
    rcp r0.w, r0.w
    mul r0.w, r0.w, r2.w
    mad r1, r0.w, c35, r1
    dp3 r3.z, r0, r0
    rsq r3.w, r3.z
    mul r0.xyz, r0, r3.w
    dp3 r0.x, r2, r0
    max r0.x, r0.x, c7.y
    mul r3.y, r3.w, r3.z
    mov r3.x, c7.z
    dp4 r0.y, c39, r3
    rcp r0.y, r0.y
    mul r0.x, r0.y, r0.x
    mad r0, r0.x, c38, r1
    add r0, r0, v2
    max r0, r0, c7.y
    min oD0, r0, c7.z
    mov oT0.xy, v3

// approximately 93 instruction slots used
