//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 viewportData;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   viewportData c9       1
//

    vs_2_0
    def c0, 0.5, 1, 0, 0
    dcl_position v0
    dcl_texcoord v1
    mad oPos.xy, v0, c9, c9.zwzw
    mov oPos.zw, c0.xyxy
    mov oT0.xy, v1

// approximately 3 instruction slots used
